# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'C:\Users\merna\Merna\Biomedical\3rd year\Term 2\MRI Dr Tamer\2 MRI simulator\MRI.ui'
#
# Created by: PyQt5 UI code generator 5.11.3
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(589, 428)
        MainWindow.setMinimumSize(QtCore.QSize(589, 428))
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout.setObjectName("gridLayout")
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setSizeConstraint(QtWidgets.QLayout.SetDefaultConstraint)
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        spacerItem = QtWidgets.QSpacerItem(13, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_5.addItem(spacerItem)
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setObjectName("label_3")
        self.horizontalLayout_5.addWidget(self.label_3, 0, QtCore.Qt.AlignRight)
        spacerItem1 = QtWidgets.QSpacerItem(20, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_5.addItem(spacerItem1)
        self.comboViewMode = QtWidgets.QComboBox(self.centralwidget)
        self.comboViewMode.setObjectName("comboViewMode")
        self.comboViewMode.addItem("")
        self.comboViewMode.addItem("")
        self.comboViewMode.addItem("")
        self.comboViewMode.addItem("")
        self.horizontalLayout_5.addWidget(self.comboViewMode)
        spacerItem2 = QtWidgets.QSpacerItem(140, 17, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_5.addItem(spacerItem2)
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_4.setObjectName("label_4")
        self.horizontalLayout_5.addWidget(self.label_4, 0, QtCore.Qt.AlignRight)
        self.TimeEcho = QtWidgets.QLineEdit(self.centralwidget)
        self.TimeEcho.setMaximumSize(QtCore.QSize(40, 15))
        self.TimeEcho.setObjectName("TimeEcho")
        self.horizontalLayout_5.addWidget(self.TimeEcho)
        spacerItem3 = QtWidgets.QSpacerItem(13, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_5.addItem(spacerItem3)
        self.label_5 = QtWidgets.QLabel(self.centralwidget)
        self.label_5.setObjectName("label_5")
        self.horizontalLayout_5.addWidget(self.label_5, 0, QtCore.Qt.AlignRight)
        self.TimeRepeat = QtWidgets.QLineEdit(self.centralwidget)
        self.TimeRepeat.setMaximumSize(QtCore.QSize(40, 15))
        self.TimeRepeat.setObjectName("TimeRepeat")
        self.horizontalLayout_5.addWidget(self.TimeRepeat)
        spacerItem4 = QtWidgets.QSpacerItem(13, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_5.addItem(spacerItem4)
        self.label_6 = QtWidgets.QLabel(self.centralwidget)
        self.label_6.setObjectName("label_6")
        self.horizontalLayout_5.addWidget(self.label_6, 0, QtCore.Qt.AlignRight)
        self.FlipAngle = QtWidgets.QLineEdit(self.centralwidget)
        self.FlipAngle.setMaximumSize(QtCore.QSize(40, 15))
        self.FlipAngle.setObjectName("FlipAngle")
        self.horizontalLayout_5.addWidget(self.FlipAngle)
        spacerItem5 = QtWidgets.QSpacerItem(13, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_5.addItem(spacerItem5)
        self.gridLayout.addLayout(self.horizontalLayout_5, 5, 1, 1, 1)
        spacerItem6 = QtWidgets.QSpacerItem(10, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem6, 3, 0, 1, 1)
        spacerItem7 = QtWidgets.QSpacerItem(20, 20, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        self.gridLayout.addItem(spacerItem7, 4, 1, 1, 1)
        spacerItem8 = QtWidgets.QSpacerItem(10, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem8, 3, 2, 1, 1)
        spacerItem9 = QtWidgets.QSpacerItem(20, 10, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        self.gridLayout.addItem(spacerItem9, 6, 1, 1, 1)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.phantomlbl = QtWidgets.QLabel(self.centralwidget)
        self.phantomlbl.setMinimumSize(QtCore.QSize(128, 128))
        self.phantomlbl.setMouseTracking(True)
        self.phantomlbl.setFrameShape(QtWidgets.QFrame.Box)
        self.phantomlbl.setText("")
        self.phantomlbl.setObjectName("phantomlbl")
        self.horizontalLayout.addWidget(self.phantomlbl)
        spacerItem10 = QtWidgets.QSpacerItem(10, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem10)
        self.verticalLayout_3 = QtWidgets.QVBoxLayout()
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.graphicsPlotT1 = PlotWidget(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.graphicsPlotT1.sizePolicy().hasHeightForWidth())
        self.graphicsPlotT1.setSizePolicy(sizePolicy)
        self.graphicsPlotT1.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.graphicsPlotT1.setObjectName("graphicsPlotT1")
        self.verticalLayout_3.addWidget(self.graphicsPlotT1)
        self.graphicsPlotT2 = PlotWidget(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.graphicsPlotT2.sizePolicy().hasHeightForWidth())
        self.graphicsPlotT2.setSizePolicy(sizePolicy)
        self.graphicsPlotT2.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.graphicsPlotT2.setObjectName("graphicsPlotT2")
        self.verticalLayout_3.addWidget(self.graphicsPlotT2)
        self.horizontalLayout.addLayout(self.verticalLayout_3)
        self.gridLayout.addLayout(self.horizontalLayout, 3, 1, 1, 1)
        spacerItem11 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        self.gridLayout.addItem(spacerItem11, 2, 1, 1, 1)
        spacerItem12 = QtWidgets.QSpacerItem(20, 10, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        self.gridLayout.addItem(spacerItem12, 0, 1, 1, 1)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.btnBrowse = QtWidgets.QPushButton(self.centralwidget)
        self.btnBrowse.setMinimumSize(QtCore.QSize(100, 0))
        self.btnBrowse.setObjectName("btnBrowse")
        self.verticalLayout.addWidget(self.btnBrowse, 0, QtCore.Qt.AlignVCenter)
        spacerItem13 = QtWidgets.QSpacerItem(20, 20, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        self.verticalLayout.addItem(spacerItem13)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.btnSheppCreate = QtWidgets.QPushButton(self.centralwidget)
        self.btnSheppCreate.setObjectName("btnSheppCreate")
        self.horizontalLayout_3.addWidget(self.btnSheppCreate)
        self.comboSheppSize = QtWidgets.QComboBox(self.centralwidget)
        self.comboSheppSize.setObjectName("comboSheppSize")
        self.comboSheppSize.addItem("")
        self.comboSheppSize.addItem("")
        self.comboSheppSize.addItem("")
        self.horizontalLayout_3.addWidget(self.comboSheppSize)
        self.verticalLayout.addLayout(self.horizontalLayout_3)
        self.horizontalLayout_2.addLayout(self.verticalLayout)
        spacerItem14 = QtWidgets.QSpacerItem(20, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem14)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setObjectName("label")
        self.horizontalLayout_4.addWidget(self.label, 0, QtCore.Qt.AlignHCenter)
        self.plotTime = QtWidgets.QLineEdit(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.plotTime.sizePolicy().hasHeightForWidth())
        self.plotTime.setSizePolicy(sizePolicy)
        self.plotTime.setMinimumSize(QtCore.QSize(40, 10))
        self.plotTime.setObjectName("plotTime")
        self.horizontalLayout_4.addWidget(self.plotTime, 0, QtCore.Qt.AlignLeft)
        self.horizontalLayout_2.addLayout(self.horizontalLayout_4)
        self.gridLayout.addLayout(self.horizontalLayout_2, 1, 1, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 589, 18))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.actionBrowse = QtWidgets.QAction(MainWindow)
        self.actionBrowse.setObjectName("actionBrowse")
        self.actionClose = QtWidgets.QAction(MainWindow)
        self.actionClose.setObjectName("actionClose")

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MRI"))
        self.label_3.setText(_translate("MainWindow", "Show"))
        self.comboViewMode.setItemText(0, _translate("MainWindow", "Phantom"))
        self.comboViewMode.setItemText(1, _translate("MainWindow", "T1"))
        self.comboViewMode.setItemText(2, _translate("MainWindow", "T2"))
        self.comboViewMode.setItemText(3, _translate("MainWindow", "PD"))
        self.label_4.setText(_translate("MainWindow", "TE"))
        self.label_5.setText(_translate("MainWindow", "TR"))
        self.label_6.setText(_translate("MainWindow", "FA"))
        self.btnBrowse.setText(_translate("MainWindow", "Browse"))
        self.btnSheppCreate.setText(_translate("MainWindow", "Shepp-Logan"))
        self.comboSheppSize.setItemText(0, _translate("MainWindow", "128"))
        self.comboSheppSize.setItemText(1, _translate("MainWindow", "256"))
        self.comboSheppSize.setItemText(2, _translate("MainWindow", "512"))
        self.label.setText(_translate("MainWindow", "Time Span"))
        self.actionBrowse.setText(_translate("MainWindow", "Browse"))
        self.actionClose.setText(_translate("MainWindow", "Close"))

from pyqtgraph import PlotWidget

if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())

