# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'C:\Users\merna\Merna\Programming\Python\MRI\MRI 1\mri.ui'
#
# Created by: PyQt5 UI code generator 5.11.3
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(525, 360)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout_10 = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout_10.setObjectName("verticalLayout_10")
        self.tabWidget = QtWidgets.QTabWidget(self.centralwidget)
        self.tabWidget.setObjectName("tabWidget")
        self.tab1 = QtWidgets.QWidget()
        self.tab1.setObjectName("tab1")
        self.verticalLayout_7 = QtWidgets.QVBoxLayout(self.tab1)
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.horizontalLayout_11 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_11.setObjectName("horizontalLayout_11")
        self.horizontalLayout_12 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_12.setObjectName("horizontalLayout_12")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout()
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.btnBrowse_3 = QtWidgets.QPushButton(self.tab1)
        self.btnBrowse_3.setMinimumSize(QtCore.QSize(100, 0))
        self.btnBrowse_3.setObjectName("btnBrowse_3")
        self.verticalLayout_5.addWidget(self.btnBrowse_3, 0, QtCore.Qt.AlignVCenter)
        spacerItem = QtWidgets.QSpacerItem(20, 20, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        self.verticalLayout_5.addItem(spacerItem)
        self.horizontalLayout_13 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_13.setObjectName("horizontalLayout_13")
        self.btnSheppCreate_3 = QtWidgets.QPushButton(self.tab1)
        self.btnSheppCreate_3.setObjectName("btnSheppCreate_3")
        self.horizontalLayout_13.addWidget(self.btnSheppCreate_3)
        self.comboSheppSize_3 = QtWidgets.QComboBox(self.tab1)
        self.comboSheppSize_3.setObjectName("comboSheppSize_3")
        self.comboSheppSize_3.addItem("")
        self.comboSheppSize_3.addItem("")
        self.comboSheppSize_3.addItem("")
        self.horizontalLayout_13.addWidget(self.comboSheppSize_3)
        self.verticalLayout_5.addLayout(self.horizontalLayout_13)
        self.horizontalLayout_12.addLayout(self.verticalLayout_5)
        spacerItem1 = QtWidgets.QSpacerItem(20, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_12.addItem(spacerItem1)
        self.label_11 = QtWidgets.QLabel(self.tab1)
        self.label_11.setObjectName("label_11")
        self.horizontalLayout_12.addWidget(self.label_11, 0, QtCore.Qt.AlignHCenter)
        self.plotTime_3 = QtWidgets.QLineEdit(self.tab1)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.plotTime_3.sizePolicy().hasHeightForWidth())
        self.plotTime_3.setSizePolicy(sizePolicy)
        self.plotTime_3.setMinimumSize(QtCore.QSize(40, 10))
        self.plotTime_3.setObjectName("plotTime_3")
        self.horizontalLayout_12.addWidget(self.plotTime_3, 0, QtCore.Qt.AlignLeft)
        self.horizontalLayout_11.addLayout(self.horizontalLayout_12)
        self.verticalLayout_7.addLayout(self.horizontalLayout_11)
        self.horizontalLayout_14 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_14.setObjectName("horizontalLayout_14")
        self.phantomlbl_3 = QtWidgets.QLabel(self.tab1)
        self.phantomlbl_3.setMinimumSize(QtCore.QSize(128, 128))
        self.phantomlbl_3.setMouseTracking(True)
        self.phantomlbl_3.setFrameShape(QtWidgets.QFrame.Box)
        self.phantomlbl_3.setText("")
        self.phantomlbl_3.setObjectName("phantomlbl_3")
        self.horizontalLayout_14.addWidget(self.phantomlbl_3)
        spacerItem2 = QtWidgets.QSpacerItem(10, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_14.addItem(spacerItem2)
        self.verticalLayout_6 = QtWidgets.QVBoxLayout()
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.graphicsPlotT1_3 = PlotWidget(self.tab1)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.graphicsPlotT1_3.sizePolicy().hasHeightForWidth())
        self.graphicsPlotT1_3.setSizePolicy(sizePolicy)
        self.graphicsPlotT1_3.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.graphicsPlotT1_3.setObjectName("graphicsPlotT1_3")
        self.verticalLayout_6.addWidget(self.graphicsPlotT1_3)
        self.graphicsPlotT2_3 = PlotWidget(self.tab1)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.graphicsPlotT2_3.sizePolicy().hasHeightForWidth())
        self.graphicsPlotT2_3.setSizePolicy(sizePolicy)
        self.graphicsPlotT2_3.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.graphicsPlotT2_3.setObjectName("graphicsPlotT2_3")
        self.verticalLayout_6.addWidget(self.graphicsPlotT2_3)
        self.horizontalLayout_14.addLayout(self.verticalLayout_6)
        self.verticalLayout_7.addLayout(self.horizontalLayout_14)
        self.horizontalLayout_15 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_15.setSizeConstraint(QtWidgets.QLayout.SetDefaultConstraint)
        self.horizontalLayout_15.setObjectName("horizontalLayout_15")
        self.label_12 = QtWidgets.QLabel(self.tab1)
        self.label_12.setObjectName("label_12")
        self.horizontalLayout_15.addWidget(self.label_12)
        spacerItem3 = QtWidgets.QSpacerItem(13, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_15.addItem(spacerItem3)
        self.comboViewMode_3 = QtWidgets.QComboBox(self.tab1)
        self.comboViewMode_3.setObjectName("comboViewMode_3")
        self.comboViewMode_3.addItem("")
        self.comboViewMode_3.addItem("")
        self.comboViewMode_3.addItem("")
        self.comboViewMode_3.addItem("")
        self.horizontalLayout_15.addWidget(self.comboViewMode_3)
        spacerItem4 = QtWidgets.QSpacerItem(140, 17, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_15.addItem(spacerItem4)
        self.label_13 = QtWidgets.QLabel(self.tab1)
        self.label_13.setObjectName("label_13")
        self.horizontalLayout_15.addWidget(self.label_13)
        self.TimeEcho_3 = QtWidgets.QLineEdit(self.tab1)
        self.TimeEcho_3.setMaximumSize(QtCore.QSize(40, 15))
        self.TimeEcho_3.setObjectName("TimeEcho_3")
        self.horizontalLayout_15.addWidget(self.TimeEcho_3)
        spacerItem5 = QtWidgets.QSpacerItem(13, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_15.addItem(spacerItem5)
        self.label_14 = QtWidgets.QLabel(self.tab1)
        self.label_14.setObjectName("label_14")
        self.horizontalLayout_15.addWidget(self.label_14)
        self.TimeRepeat_3 = QtWidgets.QLineEdit(self.tab1)
        self.TimeRepeat_3.setMaximumSize(QtCore.QSize(40, 15))
        self.TimeRepeat_3.setObjectName("TimeRepeat_3")
        self.horizontalLayout_15.addWidget(self.TimeRepeat_3)
        spacerItem6 = QtWidgets.QSpacerItem(13, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_15.addItem(spacerItem6)
        self.label_15 = QtWidgets.QLabel(self.tab1)
        self.label_15.setObjectName("label_15")
        self.horizontalLayout_15.addWidget(self.label_15)
        self.FlipAngle_3 = QtWidgets.QLineEdit(self.tab1)
        self.FlipAngle_3.setMaximumSize(QtCore.QSize(40, 15))
        self.FlipAngle_3.setObjectName("FlipAngle_3")
        self.horizontalLayout_15.addWidget(self.FlipAngle_3)
        spacerItem7 = QtWidgets.QSpacerItem(13, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_15.addItem(spacerItem7)
        self.verticalLayout_7.addLayout(self.horizontalLayout_15)
        self.tabWidget.addTab(self.tab1, "")
        self.tab2 = QtWidgets.QWidget()
        self.tab2.setObjectName("tab2")
        self.verticalLayout_9 = QtWidgets.QVBoxLayout(self.tab2)
        self.verticalLayout_9.setObjectName("verticalLayout_9")
        self.horizontalLayout_17 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_17.setObjectName("horizontalLayout_17")
        self.kspaceLbl = QtWidgets.QLabel(self.tab2)
        self.kspaceLbl.setMinimumSize(QtCore.QSize(128, 128))
        self.kspaceLbl.setMouseTracking(True)
        self.kspaceLbl.setFrameShape(QtWidgets.QFrame.Box)
        self.kspaceLbl.setText("")
        self.kspaceLbl.setObjectName("kspaceLbl")
        self.horizontalLayout_17.addWidget(self.kspaceLbl)
        spacerItem8 = QtWidgets.QSpacerItem(13, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_17.addItem(spacerItem8)
        self.imgFromKspace = QtWidgets.QLabel(self.tab2)
        self.imgFromKspace.setFrameShape(QtWidgets.QFrame.Box)
        self.imgFromKspace.setText("")
        self.imgFromKspace.setObjectName("imgFromKspace")
        self.horizontalLayout_17.addWidget(self.imgFromKspace)
        self.verticalLayout_9.addLayout(self.horizontalLayout_17)
        self.startSeq = QtWidgets.QPushButton(self.tab2)
        self.startSeq.setObjectName("startSeq")
        self.verticalLayout_9.addWidget(self.startSeq)
        self.tabWidget.addTab(self.tab2, "")
        self.verticalLayout_10.addWidget(self.tabWidget)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 525, 18))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MRI simulator"))
        self.btnBrowse_3.setText(_translate("MainWindow", "Browse"))
        self.btnSheppCreate_3.setText(_translate("MainWindow", "Shepp-Logan"))
        self.comboSheppSize_3.setItemText(0, _translate("MainWindow", "128"))
        self.comboSheppSize_3.setItemText(1, _translate("MainWindow", "256"))
        self.comboSheppSize_3.setItemText(2, _translate("MainWindow", "512"))
        self.label_11.setText(_translate("MainWindow", "Time Span"))
        self.label_12.setText(_translate("MainWindow", "Show"))
        self.comboViewMode_3.setItemText(0, _translate("MainWindow", "Phantom"))
        self.comboViewMode_3.setItemText(1, _translate("MainWindow", "T1"))
        self.comboViewMode_3.setItemText(2, _translate("MainWindow", "T2"))
        self.comboViewMode_3.setItemText(3, _translate("MainWindow", "PD"))
        self.label_13.setText(_translate("MainWindow", "TE"))
        self.label_14.setText(_translate("MainWindow", "TR"))
        self.label_15.setText(_translate("MainWindow", "FA"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab1), _translate("MainWindow", "Set Properties"))
        self.startSeq.setText(_translate("MainWindow", "Start Sequence"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab2), _translate("MainWindow", "Kspace"))

from pyqtgraph import PlotWidget

if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())

